---
title: "Repay Rate"
author: Arielle Herman
date: 2021-04-04
always_allow_html: yes
output: 
  html_document:
    keep_md: true
    toc: true
---

```{r setup, message=F, warning=F}
library(ggplot2)
library(tidyverse)

filepath <- paste0(stringr::str_remove(getwd(),"visuals"), "data/sc_repay.Rdata")
if(file.exists(filepath)) {
  load("../data/sc_repay.Rdata")
} else {
  sc_repay <- educationdata::get_education_data(level = 'college-university', source = 'scorecard',
                                              topic = 'repayment', filters = list(year = 2007:2016),
                                              add_labels = TRUE)
  save(sc_repay, file = "../data/sc_repay.Rdata")
}

scorecard <- readr::read_csv("../data/2019_College_Scorecard_Valid_Admissions_Data.csv")
```

# steps
1. list out independent variables (cohort year, year,)
2. which independent variable do I need to sum over to get 1 if I included the other group

```{r eval=F}
scorecard$CDR3
sc_repay
sc_repay %>% group_by(years_since_entering_repay, cohort_year) %>% summarize(n(), sum(repay_rate))
sc_repay %>% filter(year < cohort_year)
sc_repay
scorecard
```

```{r repay_rate, message=F, warning=F}
#selective_schools <- na.omit(scorecard$OPEID[scorecard$ADM_RATE < 0.3])
#question: select for nonprofit and private schools?
# fraction of repayment cohort that is not currently in default

sc_repay %>%
  # data wrangle
  #filter(years_since_entering_repay <= 1) %>%
  pivot_longer(cols = c("repay_rate_lowincome", "repay_rate_midincome", "repay_rate_highincome"),
               names_to = "class", values_to = "rates") %>%
  filter(rates > 0) %>%
  ## order levels to apply to multiple commands in ggplot
  mutate(class = factor(class, levels =
                          c("repay_rate_highincome", "repay_rate_midincome", "repay_rate_lowincome"))) %>%
  
  # plot
  ggplot(aes(x = year, y = rates, group = cohort_year, fill = class)) +
  geom_violin(color = "lightgray") + facet_grid(. ~ class) +
  ## themes
  ggthemes::theme_tufte() + # add base theme first and then modify
  theme(panel.spacing = unit(1, "cm"),
        panel.border = element_rect(colour = "lightgray", fill=NA, size=1),
        legend.position = "bottom",
        plot.title = element_text(hjust=0.5),
        strip.text.x = element_blank(), axis.ticks = element_blank()) +
  ## labels
  ggtitle("Fraction Of Students In Successive Fiscal Cohorts\nWhose Loan Balances Have Declined") +
  xlab(NULL) + ylab(NULL) +
  scale_fill_viridis_d(name = "Income Range:", labels = c("High Income", "Middle Income", "Low Income")) +
  ## percents
  scale_y_continuous(labels = scales::dollar_format(suffix = "%", prefix = "")) +
  scale_y_continuous(labels = scales::percent_format())
  

sc_repay %>%
  # data wrangle
  filter(repay_rate > 0, years_since_entering_repay == 1) %>%
  group_by(cohort_year, year, years_since_entering_repay) %>%
  summarize_if(is.numeric, median) %>% select(contains("year"), contains("rate")) %>%
  pivot_longer(cols = c("repay_rate_lowincome", "repay_rate_midincome",
                        "repay_rate_highincome", "repay_rate"),
               names_to = "class", values_to = "median_rates") %>%
  mutate(total = class == "repay_rate",
         class = factor(class, c("repay_rate", "repay_rate_highincome",
                                 "repay_rate_midincome", "repay_rate_lowincome"))) %>%
  # plot
  ggplot(aes(x = cohort_year, y = median_rates, group = class, color = class, alpha = total)) +
  geom_point() + geom_line() +
  #facet_wrap(. ~ factor(total, c(TRUE, FALSE))) +
  ## labels
  ggtitle("Fraction of Students whose Loan Balances Declined in their First Year of Repayment") +
  xlab("\nCohort Year") + ylab("Median Fraction of Fiscal Cohort\n") + guides(alpha = FALSE) +
  scale_color_viridis_d(name = "Family Income:",
                        labels = c("Overall", "High", "Middle", "Low")) +
  scale_y_continuous(labels = scales::dollar_format(suffix = "%", prefix = "")) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_alpha_manual(values = c(0.5, 1)) +
  ## themes
  ggthemes::theme_tufte() +
  theme(panel.spacing = unit(1, "cm"),
        #panel.border = element_rect(colour = "lightgray", fill=NA, size=1),
        legend.position = "bottom",
        plot.title = element_text(hjust=0.5),
        strip.text.x = element_blank(), axis.ticks = element_blank())
```

```{r}
sc_repay %>% #filter(cohort_year %in% 2006:2008) %>%
  
  # data wrangle
  #filter(years_since_entering_repay <= 1) %>%
  pivot_longer(cols = c("repay_rate_lowincome", "repay_rate_midincome", "repay_rate_highincome"),
               names_to = "class", values_to = "rates") %>%
  filter(rates > 0) %>%
  ## order levels to apply to multiple commands in ggplot
  mutate(class = factor(class, levels =
                          c("repay_rate_highincome", "repay_rate_midincome", "repay_rate_lowincome"))) %>%
  
  # plot
  ggplot(aes(x = rates, y = fct_rev(factor(cohort_year)), fill = class), alpha = 0.5) +
  ggridges::geom_density_ridges(scale = 2, color = "gray") +
  
  # labels
  ggtitle("Proportion of Fiscal Cohort Whose Loan Balances Have Declined") +
  ylab("Fiscal Cohort") + xlab(NULL) +
  scale_fill_brewer(name = "Family Income:", labels = c("High", "Middle", "Low"), direction = -1) +
  scale_x_continuous(labels = scales::dollar_format(suffix = "%", prefix = "")) +
  scale_x_continuous(labels = scales::percent_format()) +
  
  theme(panel.grid = element_line(color = "white"),
        text = element_text(family = "serif"),
        panel.background = element_blank(),
        legend.position = "bottom",
        axis.ticks = element_blank(),
        plot.title = element_text(hjust=0.5))
```
