---
title: "shiny_attempt1"
author: "Arielle Herman"
date: "4/18/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shinydashboard)
library(tidyverse)
library(ggridges)
library(leaflet)

source("app.R")
```


```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Group G: Student Debt"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("About", tabName = "about"),
      menuItem("Student Loans", tabName = "loans"),
      menuItem("What do people think?", tabName = "tweets"),
      menuItem("Where do people think it?", tabName = "tweetmap")
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "about", class = "active",
              fluidPage(
                tags$div(
                  tags$h1("Project Motivation"),
                  "At the end of this March, President Biden announced the cacellation of 1.3 billion dollar
                  of student loans, accompanying with a clearer picture of his overall plan on student loan.
                  While he cancelled in total of 2.3 billion dollar of student loans for more than 110,000
                  student loan borrowers and received much apprais from the group, the reaction among all the
                  Americans on this controversial issue has been quiet different. Therefore, in this project,
                  our team want to investigate further on why student loan becomes a serious problem here in US,
                  as well as how people in US has reacted to the issue based on their talk on social medis platform.
                  
                  As discussed in other sections of our repository, this project sought to explore a factors
                  related to socioeconomic conditions, student debt, inequities, and policy. This was a really
                  broad topic so we did a decent amount of exploration of the data prior to deciding on a more
                  specific topic. We tried to focus on spefic aspects of the student loan issue including university
                  selectivity, family income, repayment rate over time, and the regional differnce of debt amount to
                  understand why student debt becomes a more and more serious problem that people in US now are
                  highly concern with. After understanding the issue and recognizing the problem, we then use
                  the information from Google trend and Twitter platform to see how people reatced and talked about it.",
                  tags$h1("Sources"),
                  "For our project, we looked at data from the following sources:
                  (1) Scorecard, (2) Urban Institute Education Data, (3) Twitter API, and (4) Google Trends",
                  tags$h1("Team Members"),
                  "Arielle Herman, Connie Xu, Grace Li, Ariel Luo"
                )
              )),
      tabItem(tabName = "loans", class = "active",
        fluidPage(
          tags$div(
            tags$h1("Repayment Rates", align = "center")),
          fluidRow(align = "left",
                   column(8, wellPanel(plotOutput("repay_rate_ave"))),
                   column(4, wellPanel(p("This first figure demonstrates the proportion of students across all University
                               fiscal cohorts who successfully make progress on repaying their loans in their
                               first year of repayment.  It highlights a declining average trend across all three income
                               brackets: smaller proportions of successive fiscal cohorts decline their loan
                               balances over time.  While the average fiscal cohort may be having more difficulty in
                               repaying their loans, we can look to the distribution of repayment rates across
                               universities in order to determine whether or not income brackets have been impacted
                               differently over time.")), style='padding:5px;'),
                   br()),
          fluidRow(align = "left",
                   column(4, wellPanel(p("This density plot demonstrates the distribution of repayment proportions across
                   universities for the first year of repayment for recent fiscal cohorts.  Each unviersity's fiscal 
                   cohort is then further subdivided by income bracket (such that there can be as many as three 
                   datapoints per university).  This reaffirms the findings in the previous plot, but also indicates
                   that the lowest income bracket has experienced the largest decrease in proportions of students who
                   make progress on their loans."))),
                   column(8, wellPanel(plotOutput("repay_rate_dist")))),
          tags$div(
            tags$h1("University Selectivity and Student Debt", align = "center"),
            tags$h3("University Selectivity")),
        fluidRow(align = "left",
                 column(7, wellPanel(DTOutput("table"))),
                 column(5, wellPanel(p("We will now examine the relationships between student loans and the 'selectiveness'
                 of the universities in our dataset. Selectiveness (admissions rate) is often a proxy for the prestige
                 \"ranking\" of a school. This table summarizes how we categorized our admissions rate for 'university
                 selectivity' grouping (from the College Scorecard file). It describes the median student loans and the
                 number of universities in each category as of 2019, as well as the Minimum Acceptance Rate, and the Maximum
                 Acceptance Rate thresholds. As shown (left), the vast majority of schools in our dataset were 'not
                 selective' or 'less selective'; however, many of our analyses focus on the smaller categories (particularly
                 selective to highly selective/elite), because these categories have more within-group homogeneity and
                 furthermore are more interesting to our focal questions.")))),
                 #column(4, wellPanel(highcart2Output("treemap")))), # finish output function
        fluidRow(align = "left",
                 column(4, wellPanel(p("  This plot sets out to show the relationship between median loan amount in 2019 and
                 the admissions rate. The trend shown here is that as the admissions rate goes up (i.e., as schools become
                 less selective), so does median loan amount (at least until we go from less selective to not selective).
                 Based on the scatterplot, it can also be seen that the variance goes up in terms of median student loan
                 amount (although it can also be seen that this is partially due to the much larger number of schools in the
                 less selective buckets).  
                   
                 This is somewhat interesting because more exclusive/selective schools are on average viewed as more
                 'competitive' and 'prestigious' (e.g., Harvard, Stanford, etc.); a great deal of existent literature has
                 noted that such 'prestigious' schools often end up admitting more people from economically privileged
                 backgrounds (outside of those admitted specifically for diversity), as 'merit-based' admissions often
                 correlate with access to economic and financial resources, which allow for access to resources helpful for
                 competence signalling, such as standardized test prep courses, sports and activities, etc; furthermore, such
                 schools include more financial resources (as more prestigious schools produce alma maters with higher
                 socioeconomic outcomes) and thus potentially can help more with financial aid and scholarships."))),
                 column(8, wellPanel(plotOutput("admissions_scatter")))),
        fluidRow(align = "left",
                 column(12, wellPanel(plotlyOutput("plotly")))),
        fluidRow(column(4, wellPanel(sliderInput(inputId = "year",
                                                  label = "Year",
                                                  value = 2019, min = 2010, max = 2019, sep = ''))),
                 column(8, wellPanel(p("  Between 2010 and 2018, the median loan amount per student increased by 2000-4000+
                 USD (inflation-adjusted) - nationally, the median student loan amount increased by 19%. When one
                 disaggregates universities by selectivity, we see the same *overall* trend over time (i.e., there is a fair
                 amount of increase during the period in terms of average student loans that students leave with upon
                 entering repayment); however, some selectivity groups increased more dramatically than others (e.g., 'More
                 Selective' or schools with 20-30% acceptance rates appeared to increase greatly in terms of student debt
                 principal between 2015 and 2017, but this amount declined a bit again in 2018) and different selectivity
                 groups decreased in median student debt over time (less selective; selective schools seemed to decrease in
                 median debt following 2014).  
                   
                To look at how median student debt has changed either by only national average or to look at specific
                'selectivity' buckets, one can simply click to remove the remaining lines in the plot."))),
                 column(12, wellPanel(leafletOutput("studentdebtmap")))),
        fluidRow(column(12, wellPanel(p("Not all schools have similar amounts of median student debt burden (i.e., upon the
        beginning of the repayment period). This map summarizes the median debt burden by the state that the school is
        located in. As shown in this plot, some states (including schools in Pennsylvania, Minnesota, Illinois, etc.) tend to
        have the highest average median debt burden between the schools within. These states do not necessarily house the
        most prestigious schools. One of the things we can see when disaggregating this way is that locationally there is a
        lot of diversity of the student loan burden (on average) given to students by schools when disaggregated at the state
        level (ranging from 4K to 18K USD in 2019)
          
        Note that we have also included the shiny interactivity component in which one can select the year on the slider to
        see the state-level debt median disaggregation across the years; this is not the primary function but instead is a
        functionality we added to allow individuals to 'explore the data' a bit.")))))),
      tabItem(tabName = "tweets", class = "active",
          fluidPage(
            fluidRow(align = "left",
                    column(6, wellPanel(plotOutput("trend"))),
                    column(6, wellPanel(wordcloud2Output("wordcloud")))),
            fluidRow(align = "left",
                     column(6, wellPanel(p("The google trend website gives us data about the time period and the count of
                                 total number of searches on Google. Plotting the total number of searches overtime
                                 helps us to see changes in people's interest in student loan forgiveness. The pattern
                                 clearly shows that people's interest in this topic has spiked in 2021. We hypothesized
                                 that this is a result of the Biden administration's recent announcement of a
                                 reinterpretation of a federal student loan cancellation program which will result in
                                 $1 billion in student loan forgiveness. Ever since this announcement, more people have
                                 been pushing for a more progressive policy and asking President Biden to cancel student
                                 debt through executive action. There is still a lot of uncertainties around whether a
                                 universal student loan forgiveness will be initiated via an executive order or via
                                 legislation." ))),
                     column(6, wellPanel(p("The wordcloud map shows key words that appeared in the tweets data. The size of the
                                 word represents how frequently it appears in tweets. Some of the most noticeable ones
                                 include people, president, loans, job, college, pay, biden, education,
                                 studentloanforgiveness, etc. This keywords pattern confirms our initial hypothesis that
                                 the recent discussion on canceling student debt on twitter is around the biden
                                 administration as a result of the $1B student loan cancellation announced in
                                 Mid-march.")))))),
      tabItem(tabName = "tweetmap", class = "active",
          fluidPage(
            fluidRow(column(12, wellPanel(leafletOutput("tweetsmap")))),
            fluidRow(align = "left",
                     column(12, wellPanel(p("Lastly, we want to see if there's an overlap between the states that are most
                     concerned about student loan forgiveness and where the selective schools are located. We added
                     two layers on the map to showcase patterns. The first layer tells us which states are most
                     concerned about student loan forgiveness by setting the radius of the circle to the total
                     tweets word count. The gradient color scale shows the sentiment score of each state where
                     red means a more negative average tweets sentiment and green means a more positive tweet
                     sentiment on average. In addition, the popup window shows the top tweets keywords in each
                     state after getting ride of most frequent keywords such as student, loan, debt,
                     cancelstudentdebt, and amp. In California, not only do people tweet the most about student
                     loan forgiveness, but they also have a more positive sentiment toward student loan forgiveness.
                     Other areas where there are more discussions on student loan forgiveness concentrate along the
                     coastal states. Midwestern states are least concerned about student loan forgiveness, and their
                     tweets sentiment is also more negative.
                     
                     The second layer shows where the selective institutions are located, where purple icon stands
                     for elite universities, green icon stands for highly selective universities, and blue icon
                     stands for selective universities. Overall, these selective universities are concentrated along the
                     coastlines. On the west coast, most of the selective universities are in California. And the
                     selective universities spread out more evenly on the east coast. Overall, we can see an overlap
                     by looking at the two layers together. States with higher concentration of selective schools
                     are also where people are most concerned about student loan forgiveness."))))))
      ) # tabItems
    ) # dashboard Body
  ) # ui?
)

server <- function(input, output) {
  #library(tidyverse)
  # arielle ~~~~~~~~~~~~~~~~~~~~~
  output$repay_rate_ave <- renderPlot({
    repay_rate_ave
    
  })
  output$repay_rate_dist <- renderPlot({
    repay_rate_dist
    })
  # grace ~~~~~~~~~~~~~~~~~~~~~~~
  
  output$trend <- renderPlot({
    Trend
  })
  
  output$wordcloud <- wordcloud2::renderWordcloud2({
    Twitter_wd
  })
  
  output$tweetsmap <- leaflet::renderLeaflet({
    TweetsMap
  })
  
  # Connie ~~~~~~~~~~~~~~~~~~~~~~~
  
  output$table <- renderDT(
    table_1
  )
  
  #output$treemap <- renderHighchart2(
  #  treemap
  #)
  output$admissions_scatter <- renderPlot({
    admissions_scatter
  })
  
  output$plotly <- renderPlotly({
    plot_line_plotly
  })
  
  
# connie map prep code data wrangle
  sc_time_selective <- reactive({sc_time %>% subset(Year_Ending == input$year) %>%
      group_by(STABBR) %>% mutate(`Average Student Loans`=sum(DEBT_MDN_STUDENT,na.rm=TRUE)/sum(UGDS,na.rm=TRUE)) %>%
      group_by(STABBR,`Average Student Loans`) %>% summarize()})
  states <- states(cb = TRUE)
  states_year <- reactive({states %>% inner_join(sc_time_selective(), by=c(STUSPS='STABBR'))}) 
  
# render output
  output$studentdebtmap <- renderLeaflet({
    pal = colorFactor('Greens', domain = states_year()$`Average Student Loans`)
    pop_pop <- paste("State:",states_year()$NAME,"<br/>",
                     "Average Student Loans","<br/>", "of Schools Located in State:",
                     paste('$',round(states_year()$`Average Student Loans`)))
    
    sc_time_selective_title <- tags$p(tags$style('p{color:gray; font-size: 14px; family: serif}'),
                                      tags$b('Average Debt By State (2019)'))
    leaflet(states_year()) %>% addProviderTiles("CartoDB.Positron") %>%
      addPolygons(fillColor = ~pal(states_year()$`Average Student Loans`),
                  color = "white",
                  weight = 0.5,
                  fillOpacity = 0.7,  
                  highlight = highlightOptions(
                    weight = 5,
                    color = "#666",
                    fillOpacity = 0.7,
                    bringToFront = TRUE,
                  ),popup=pop_pop) %>% leaflet::addLegend(position = "bottomleft", colors =c("#EDF8E9","#BAE4B3","#74C476","#31A354","#006D2C"), 
                                                 labels = c(paste('$',round(min(states_year()$`Average Student Loans`)))," "," "," ", 
                                                            paste('$',round(max(states_year()$`Average Student Loans`)))),
                                                 title = "Average Student Loans (Per Student)") %>%
      leaflet::setView(-98.5795, 39.8282, zoom=3) %>% addControl(sc_time_selective_title, position='topright')
  })
# observe leaflet output  
  observe({
    leafletProxy("studentdebtmap", data = states_year())
  })
  
}

shinyApp(server = server, ui = ui)

```